item_deps = {
        "T3_BAG": ["T3_CLOTH", "T3_LEATHER"],
        "T4_BAG": ["T4_CLOTH", "T4_LEATHER"],
        "T5_BAG": ["T5_CLOTH", "T5_LEATHER"],
        "T6_BAG": ["T6_CLOTH", "T6_LEATHER"],
        "T7_BAG": ["T7_CLOTH", "T7_LEATHER"],
        "T8_BAG": ["T8_CLOTH", "T8_LEATHER"],
        }

item_id = \
"T3_BAG,T3_CLOTH,T3_LEATHER,\
T4_BAG,T4_CLOTH,T4_LEATHER,\
T5_BAG,T5_CLOTH,T5_LEATHER,\
T6_BAG,T6_CLOTH,T6_LEATHER,\
T7_BAG,T7_CLOTH,T7_LEATHER,\
T8_BAG,T8_CLOTH,T8_LEATHER,\
T3_MAIN_ARCANESTAFF,T4_MAIN_ARCANESTAFF,T5_MAIN_ARCANESTAFF,\
T6_MAIN_ARCANESTAFF,T7_MAIN_ARCANESTAFF,T8_MAIN_ARCANESTAFF\
T3_MAIN_CURSEDSTAFF,T4_MAIN_CURSEDSTAFF,T5_MAIN_CURSEDSTAFF,\
T6_MAIN_CURSEDSTAFF,T7_MAIN_CURSEDSTAFF,T8_MAIN_CURSEDSTAFF\
"

complex_items = [
        "T4_BAG", "T5_BAG", "T6_BAG", "T7_BAG", "T8_BAG", "T3_BAG",
        ]
